server:
  port: 9095
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: cloud